### ISSUE TITLE
Not an issue, but a thank you word!

### ISSUE THREAD

**Issue by loneicewolf** [CPScript/PythoniC#2]
Thanks for making this repo, not only because it's both interesting but a question, could you provide some resources you used while creating it? You do state it's based on Petya **(..)** but no reference to really how? Would just be interesting, no pressure! `:)`

Thanks again and

**Comment by loneicewolf** [comment]
forgot to add this 'issue' can be closed. Just wanted to show my appreciation. 💯

**Comment by 0u44** [comment]
> Thanks for making this repo, not only because it's both interesting but a question, could you provide some resources you used while creating it? You do state it's based on Petya **(..)** but no reference to really how? Would just be interesting, no pressure! `:)`
> 
> Thanks again and
> 
> ## Wishes from Sweden!

i don't rly remember what i used... i know someone helped me make it and that i used petya's source code for some of it

**Comment by loneicewolf** [comment]
oh okay, it's all good, thanks anyway! `:)` @CPScript
